# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/mint/Documents/GitHub/Phaistos

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/mint/Documents/GitHub/Phaistos

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mint/Documents/GitHub/Phaistos/CMakeFiles /home/mint/Documents/GitHub/Phaistos//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/mint/Documents/GitHub/Phaistos/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named phaistos

# Build rule for target.
phaistos: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 phaistos
.PHONY : phaistos

# fast build rule for target.
phaistos/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/build
.PHONY : phaistos/fast

src/cpu.o: src/cpu.cpp.o
.PHONY : src/cpu.o

# target to build an object file
src/cpu.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/cpu.cpp.o
.PHONY : src/cpu.cpp.o

src/cpu.i: src/cpu.cpp.i
.PHONY : src/cpu.i

# target to preprocess a source file
src/cpu.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/cpu.cpp.i
.PHONY : src/cpu.cpp.i

src/cpu.s: src/cpu.cpp.s
.PHONY : src/cpu.s

# target to generate assembly for a file
src/cpu.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/cpu.cpp.s
.PHONY : src/cpu.cpp.s

src/fake6502/fake6502.o: src/fake6502/fake6502.cpp.o
.PHONY : src/fake6502/fake6502.o

# target to build an object file
src/fake6502/fake6502.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/fake6502/fake6502.cpp.o
.PHONY : src/fake6502/fake6502.cpp.o

src/fake6502/fake6502.i: src/fake6502/fake6502.cpp.i
.PHONY : src/fake6502/fake6502.i

# target to preprocess a source file
src/fake6502/fake6502.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/fake6502/fake6502.cpp.i
.PHONY : src/fake6502/fake6502.cpp.i

src/fake6502/fake6502.s: src/fake6502/fake6502.cpp.s
.PHONY : src/fake6502/fake6502.s

# target to generate assembly for a file
src/fake6502/fake6502.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/fake6502/fake6502.cpp.s
.PHONY : src/fake6502/fake6502.cpp.s

src/logger.o: src/logger.cpp.o
.PHONY : src/logger.o

# target to build an object file
src/logger.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/logger.cpp.o
.PHONY : src/logger.cpp.o

src/logger.i: src/logger.cpp.i
.PHONY : src/logger.i

# target to preprocess a source file
src/logger.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/logger.cpp.i
.PHONY : src/logger.cpp.i

src/logger.s: src/logger.cpp.s
.PHONY : src/logger.s

# target to generate assembly for a file
src/logger.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/logger.cpp.s
.PHONY : src/logger.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/optimizer.o: src/optimizer.cpp.o
.PHONY : src/optimizer.o

# target to build an object file
src/optimizer.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/optimizer.cpp.o
.PHONY : src/optimizer.cpp.o

src/optimizer.i: src/optimizer.cpp.i
.PHONY : src/optimizer.i

# target to preprocess a source file
src/optimizer.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/optimizer.cpp.i
.PHONY : src/optimizer.cpp.i

src/optimizer.s: src/optimizer.cpp.s
.PHONY : src/optimizer.s

# target to generate assembly for a file
src/optimizer.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/optimizer.cpp.s
.PHONY : src/optimizer.cpp.s

src/parser.o: src/parser.cpp.o
.PHONY : src/parser.o

# target to build an object file
src/parser.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/parser.cpp.o
.PHONY : src/parser.cpp.o

src/parser.i: src/parser.cpp.i
.PHONY : src/parser.i

# target to preprocess a source file
src/parser.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/parser.cpp.i
.PHONY : src/parser.cpp.i

src/parser.s: src/parser.cpp.s
.PHONY : src/parser.s

# target to generate assembly for a file
src/parser.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/parser.cpp.s
.PHONY : src/parser.cpp.s

src/sequence_generator.o: src/sequence_generator.cpp.o
.PHONY : src/sequence_generator.o

# target to build an object file
src/sequence_generator.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/sequence_generator.cpp.o
.PHONY : src/sequence_generator.cpp.o

src/sequence_generator.i: src/sequence_generator.cpp.i
.PHONY : src/sequence_generator.i

# target to preprocess a source file
src/sequence_generator.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/sequence_generator.cpp.i
.PHONY : src/sequence_generator.cpp.i

src/sequence_generator.s: src/sequence_generator.cpp.s
.PHONY : src/sequence_generator.s

# target to generate assembly for a file
src/sequence_generator.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/sequence_generator.cpp.s
.PHONY : src/sequence_generator.cpp.s

src/solution_formatter.o: src/solution_formatter.cpp.o
.PHONY : src/solution_formatter.o

# target to build an object file
src/solution_formatter.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/solution_formatter.cpp.o
.PHONY : src/solution_formatter.cpp.o

src/solution_formatter.i: src/solution_formatter.cpp.i
.PHONY : src/solution_formatter.i

# target to preprocess a source file
src/solution_formatter.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/solution_formatter.cpp.i
.PHONY : src/solution_formatter.cpp.i

src/solution_formatter.s: src/solution_formatter.cpp.s
.PHONY : src/solution_formatter.s

# target to generate assembly for a file
src/solution_formatter.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/solution_formatter.cpp.s
.PHONY : src/solution_formatter.cpp.s

src/transformation_cache.o: src/transformation_cache.cpp.o
.PHONY : src/transformation_cache.o

# target to build an object file
src/transformation_cache.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/transformation_cache.cpp.o
.PHONY : src/transformation_cache.cpp.o

src/transformation_cache.i: src/transformation_cache.cpp.i
.PHONY : src/transformation_cache.i

# target to preprocess a source file
src/transformation_cache.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/transformation_cache.cpp.i
.PHONY : src/transformation_cache.cpp.i

src/transformation_cache.s: src/transformation_cache.cpp.s
.PHONY : src/transformation_cache.s

# target to generate assembly for a file
src/transformation_cache.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/transformation_cache.cpp.s
.PHONY : src/transformation_cache.cpp.s

src/value.o: src/value.cpp.o
.PHONY : src/value.o

# target to build an object file
src/value.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/value.cpp.o
.PHONY : src/value.cpp.o

src/value.i: src/value.cpp.i
.PHONY : src/value.i

# target to preprocess a source file
src/value.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/value.cpp.i
.PHONY : src/value.cpp.i

src/value.s: src/value.cpp.s
.PHONY : src/value.s

# target to generate assembly for a file
src/value.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/value.cpp.s
.PHONY : src/value.cpp.s

src/verification_engine.o: src/verification_engine.cpp.o
.PHONY : src/verification_engine.o

# target to build an object file
src/verification_engine.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/verification_engine.cpp.o
.PHONY : src/verification_engine.cpp.o

src/verification_engine.i: src/verification_engine.cpp.i
.PHONY : src/verification_engine.i

# target to preprocess a source file
src/verification_engine.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/verification_engine.cpp.i
.PHONY : src/verification_engine.cpp.i

src/verification_engine.s: src/verification_engine.cpp.s
.PHONY : src/verification_engine.s

# target to generate assembly for a file
src/verification_engine.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/phaistos.dir/build.make CMakeFiles/phaistos.dir/src/verification_engine.cpp.s
.PHONY : src/verification_engine.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... phaistos"
	@echo "... src/cpu.o"
	@echo "... src/cpu.i"
	@echo "... src/cpu.s"
	@echo "... src/fake6502/fake6502.o"
	@echo "... src/fake6502/fake6502.i"
	@echo "... src/fake6502/fake6502.s"
	@echo "... src/logger.o"
	@echo "... src/logger.i"
	@echo "... src/logger.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/optimizer.o"
	@echo "... src/optimizer.i"
	@echo "... src/optimizer.s"
	@echo "... src/parser.o"
	@echo "... src/parser.i"
	@echo "... src/parser.s"
	@echo "... src/sequence_generator.o"
	@echo "... src/sequence_generator.i"
	@echo "... src/sequence_generator.s"
	@echo "... src/solution_formatter.o"
	@echo "... src/solution_formatter.i"
	@echo "... src/solution_formatter.s"
	@echo "... src/transformation_cache.o"
	@echo "... src/transformation_cache.i"
	@echo "... src/transformation_cache.s"
	@echo "... src/value.o"
	@echo "... src/value.i"
	@echo "... src/value.s"
	@echo "... src/verification_engine.o"
	@echo "... src/verification_engine.i"
	@echo "... src/verification_engine.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

